version: 2.1

jobs:
  build:
    docker:
      - image: alpine:3.14
    working_directory: /tmp/build
    steps:
      - checkout
      - run:
          name: "Install curl"
          command: "apk update && apk add curl"
      - run:
          name: "Download Zig"
          command: "curl -s -N https://ziglang.org/download/0.9.0/zig-linux-x86_64-0.9.0.tar.xz | tar Jx"
      - run:
          name: "Build Debug"
          command: "zig-linux-x86_64-0.9.0/zig build bin install -p Debug"
      - run:
          name: "Build Release"
          command: "zig-linux-x86_64-0.9.0/zig build bin install -Drelease-fast=true -p Release"
      - store_artifacts:
          path: /tmp/build/Debug
          destination: Debug
      - store_artifacts:
          path: /tmp/build/Release
          destination: Release

workflows:
  workflow:
    jobs:
      - build
